### ISSUE TITLE
Mentors for Code-and-Learn @ NodeConf EU (Nov 5)

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/code-and-learn#81]
Hey @nodejs/collaborators, on NodeConf EU in Ireland we'll have a Code-and-Learn event and we are looking for further mentors. 

Right now we have three mentors and it would be good to have 10 (I expect to have around 50 attendees).

If you come to NodeConf EU, and you want to help new people get involved with Node.js core please leave a comment here. Thanks!

// cc @hackygolucky @addaleax @mhdawson @trivikr @mafintosh @BethGriggs @gabrielschulhof @sebdeckers 

## Mentors

- [x] @jasnell
- [x] @mcollina 
- [x] @BridgeAR
- [x] @mhdawson 
- [x] @trivikr
- [x] @addaleax
- [x] @mike-kaufman
- [x] @sebdeckers 
- [x] @gabrielschulhof
- [x]  @gdams 
- [ ] you? 
- [ ] you? 

## Day-of Agenda

Nov. 5, 2018

# TODOs

- [ ] Defining all tasks
- [ ] Finding enough mentors
- [ ] Write a proper summary
- ...

**Comment by MylesBorins** [comment]
o/

**Comment by trivikr** [comment]
In 👍

**Comment by addaleax** [comment]
Yup, me too! /cc @nodejs/code-and-learn

**Comment by trivikr** [comment]
NodeConf EU schedule is up at https://www.nodeconf.eu/, and as per the schedule Code&Learn will be on Tuesday November 6th from 2pm-3:30pm and 4pm-5:30pm

**Comment by trivikr** [comment]
One of the learnings from NodeJSInteractive Code-and-Learn was that it was not obvious for participants to find out who the mentors are (https://github.com/nodejs/code-and-learn/issues/86#issuecomment-430369958) 

Should we have separate T-Shirts for mentors at NodeConf EU Code-and-Learn? :smile: 
cc @BridgeAR

**Comment by sebdeckers** [comment]
👍🏻 ... and my hacks!

**Comment by gabrielschulhof** [comment]
I'd also like to help out 👍

**Comment by BridgeAR** [comment]
Thanks a lot to everyone!
